apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: astkiw4qq-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: astkiw4qq-nodejs 
  name: astkiw4qq-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: astkiw4qq-nodejs 
